### ISSUE TITLE
macosx screenshots and possible bug

### ISSUE THREAD

**Issue by stoneface86** [neroist/uing#4]
Was trying out this library on a Mac VM since there aren't any screenshots yet and I noticed a weird layout issue on the second page of `controlgallery3.nim`. I took screenshots of all three tabs if you want to use them.

![macosx1](https://github.com/neroist/uing/assets/44489054/bc3b8289-f7e7-4ffe-a662-be4f262f839b)

Problem is here, it lays out the radio buttons with some vertical spacing in between the third one for some reason. Dunno if this is an issue with ui-ng, the wrapper, or the example program:

![macosx2](https://github.com/neroist/uing/assets/44489054/0eb93872-24ce-4e50-8fae-ab207737fa3f)
![macosx3](https://github.com/neroist/uing/assets/44489054/c14d37a7-e567-454f-9c06-a98e2a4b6450)

The problem goes away when resizing the window, but reappears when switching tabs. I am using a VM of Mojave (10.14.4).

**Comment by neroist** [comment]
Try compiling and running the original C example and see if the issue still appears. If so, file an issue on the libui-ng repo. Also, thank you for the screenshots! It would be also appreciated if you could also get some screenshots of the other example programs!

**Comment by stoneface86** [comment]
Yup, same issue appears in the libui-ng repo. At least it does on monterey, I gave up trying to compile it on mojave.

Here's some screenshots of the other example programs:
 
![controllgallery](https://github.com/neroist/uing/assets/44489054/4ed9ac34-a66e-4b4a-99d0-5299e57459b2)
![datetime](https://github.com/neroist/uing/assets/44489054/9179a005-3f6e-4d87-9258-dbae6e36e493)
![drawtext](https://github.com/neroist/uing/assets/44489054/b42e21b1-9729-4dc9-924d-69dfc72fc504)
![gradient](https://github.com/neroist/uing/assets/44489054/7ac222a0-e23a-42b0-ac74-f57313ddfd4e)
![hellowworld](https://github.com/neroist/uing/assets/44489054/2f3b2d8f-336f-4fb0-87de-4bc08dd248e7)
![histogram](https://github.com/neroist/uing/assets/44489054/53e3d85c-49cb-4545-bbc6-0da4776c922e)
![menus1](https://github.com/neroist/uing/assets/44489054/7aeee900-7f3e-4a31-88b3-dc2451acbdcd)
![menus2](https://github.com/neroist/uing/assets/44489054/06423c7f-46e4-4ea7-8ca3-4ceb8631cdce)
![squares](https://github.com/neroist/uing/assets/44489054/198a4cef-a0b4-4ef3-ba95-ff8caeb7d0c4)

**Comment by neroist** [comment]
Thank you for the extra screenshots! Since this seems to be an issue with libui-ng itself and not the wrapper, I'll be closing this. 

Perhaps you should file an issue about your trouble compiling on mojave too on libui-ng's repo too.
