### ISSUE TITLE
finally a good nim UI lib

### ISSUE THREAD

**Issue by ghost** [neroist/uing#6]
thank you neroist for making bindings for this lib! now i can finally enjoy some gui programming in nim :)

cheers!

**Comment by neroist** [comment]
You're welcome! I'm really glad you like my bindings! Honestly, I'm surprised that someone else hadn't tried to create similar bindings earlier.

**Comment by ghost** [comment]
> You're welcome! I'm really glad you like my bindings! Honestly, I'm surprised that someone else hadn't tried to create similar bindings earlier.

ofc your always carrying the nim community :)

**Comment by neroist** [comment]
You flatter me, thank you ! :)
